LineLength:
  Max: 100

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

ClassAndModuleChildren:
  Enabled: false

TrailingCommaInLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2.2
